.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "WAIT\-SERVER" "1" "March 2019" "" ""
.
.SH "NAME"
\fBwait\-server\fR \- Test and wait for server availability
.
.SH "SYNOPSIS"
\fBwait\-server\fR [[HOST] PORT] [\-t \fItimeout\fR][\-q][\-h]
.
.SH "DESCRIPTION"
\fBwait\-server\fR tries connecting to port \fBPORT\fR at \fBHOST\fR (a domain name or IP address) in 5 seconds\. Before that time is exhausted, if the port is connected successfully, \fBwait\-server\fR will exit with success status (\fB0\fR), otherwise, it will exit with error status (\fB1\fR)\. You can change the timeout with option \fB\-t\fR\.
.
.SH "ARGUMENTS"
.
.TP
\fBPORT\fR
TCP port where the server is supposed to listen\. Default to 8000\.
.
.TP
\fBHOST\fR
Hostname or IP address of the server\. Default to \fBlocalhost\fR\. Note that when this argument is given, you must provide \fBPORT\fR\.
.
.SH "OPTIONS"
.
.TP
\fB\-t\fR
Duration in second to test connectivity, before exiting\. \fBwait\-server\fR will retry to connect every second in this time range\.
.
.TP
\fB\-q\fR
Quiet\. If this option is absent, the tool will show a sequence of dots to indicate its progress\.
.
.TP
\fB\-h\fR
Show help and exit\.
.
.SH "EXAMPLES"
.
.nf

$ wait\-server 5000
$ wait\-server agriconnect\.vn 80
$ wait\-server 8086 \-t 10
.
.fi
.
.P
Main purpose of this tool, is to be used in a \fIsystemd\fR service, to delay the service until some server is online\. For example, you have \fBservice\-a\fR and \fBservice\-b\fR, in which \fBservice\-a\fR is a server software that takes long time to initialize (often Java application), and \fBservice\-b\fR should be run only after \fBservice\-a\fR is ready\. You can write the \fIsystemd\fR service file like this:
.
.IP "" 4
.
.nf

[Unit]
After=service\-a\.service

[Service]
ExecStartPre=/usr/bin/wait\-server
ExecStart=/usr/bin/application\-b
.
.fi
.
.IP "" 0

